apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-igql
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-igql
    app.kubernetes.io/part-of: tkrw-pr712-0075-0010-app
  name: devfile-sample-igql
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-igql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-igql
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0010-tenant/tkrw-pr712-0075-0010-app/devfile-sample-igql@sha256:d6d5839b11a10025183e9209e5e8d6675fba23af223b64b44791f3f88a8ac098
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
